print('hello word')
print('tunan')
print(233)
print(2.330)
print(True)
print(None)
type('hello word')
print(type(None))
print(10%4)
print('tunan')
print('图南')
print(379)
print(3.79)
print(True)
print(False)
print(None)
a = type('tunan')
print(a)
print(379%3)
x = int(input('x='))
y = int(input('y='))
z = int(input('z='))
m = int(input('m='))
n = int(input('n='))
print(x*(y+z)/(m-n))
bool(input(False))
b = len('tuanaafsdja')
print(b) 